export enum SessionType {
  CONTINUOUS = 'CONTINUOUS',
  /**
   * @deprecated Use MANUAL instead
   */
  PLAIN = 'MANUAL',
  MANUAL = 'MANUAL',

  CONTINUOUS_SESSION_CACHE = 'CONTINUOUS_SESSION_CACHE',
  SESSION_CACHE = 'SESSION_CACHE',
}
