const tsPlugin = require('@typescript-eslint/eslint-plugin')
const tsParser = require('@typescript-eslint/parser')

// Equivalent to env: { es6: true, node: true, jest: true, mocha: true }
const envGlobals = {
  // Node.js
  __dirname: 'readonly',
  __filename: 'readonly',
  Buffer: 'readonly',
  clearImmediate: 'readonly',
  clearInterval: 'readonly',
  clearTimeout: 'readonly',
  console: 'readonly',
  exports: 'writable',
  global: 'readonly',
  module: 'writable',
  process: 'readonly',
  require: 'readonly',
  setImmediate: 'readonly',
  setInterval: 'readonly',
  setTimeout: 'readonly',
  URL: 'readonly',
  URLSearchParams: 'readonly',
  // Jest
  afterAll: 'readonly',
  afterEach: 'readonly',
  beforeAll: 'readonly',
  beforeEach: 'readonly',
  describe: 'readonly',
  expect: 'readonly',
  fit: 'readonly',
  it: 'readonly',
  jest: 'readonly',
  test: 'readonly',
  xdescribe: 'readonly',
  xit: 'readonly',
  xtest: 'readonly',
  // Mocha
  after: 'readonly',
  before: 'readonly',
  context: 'readonly',
  mocha: 'readonly',
  run: 'readonly',
  specify: 'readonly',
  suite: 'readonly',
  suiteSetup: 'readonly',
  suiteTeardown: 'readonly',
  xcontext: 'readonly',
  xspecify: 'readonly',
}

module.exports = [
  {
    ignores: [
      'package.json',
      'node_modules/**',
      'clients/**',
      'libs/multiplayer-blocknote-lib/**',
      '**/dist/**',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.mts', '**/*.cts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: envGlobals,
    },
    plugins: {
      '@typescript-eslint': tsPlugin,
    },
    rules: {
      // plugin:@typescript-eslint/eslint-recommended — disables ESLint rules
      // that TypeScript handles natively, enables TS-aware replacements
      'constructor-super': 'off',
      'getter-return': 'off',
      'no-const-assign': 'off',
      'no-dupe-args': 'off',
      'no-dupe-class-members': 'off',
      'no-dupe-keys': 'off',
      'no-func-assign': 'off',
      'no-import-assign': 'off',
      'no-new-symbol': 'off',
      'no-obj-calls': 'off',
      'no-redeclare': 'off',
      'no-setter-return': 'off',
      'no-this-before-super': 'off',
      'no-undef': 'off',
      'no-unreachable': 'off',
      'no-unsafe-negation': 'off',
      'no-var': 'error',
      'prefer-rest-params': 'error',
      'prefer-spread': 'error',
      // plugin:@typescript-eslint/recommended
      '@typescript-eslint/ban-ts-comment': 'error',
      'no-array-constructor': 'off',
      '@typescript-eslint/no-array-constructor': 'error',
      '@typescript-eslint/no-duplicate-enum-values': 'error',
      '@typescript-eslint/no-extra-non-null-assertion': 'error',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
      '@typescript-eslint/no-this-alias': 'error',
      '@typescript-eslint/no-unnecessary-type-constraint': 'error',
      '@typescript-eslint/no-unsafe-declaration-merging': 'error',
      '@typescript-eslint/no-var-requires': 'error',
      '@typescript-eslint/prefer-as-const': 'error',
      '@typescript-eslint/triple-slash-reference': 'error',
      // Custom rules (from .eslintrc)
      'prefer-const': 'error',
      '@typescript-eslint/no-namespace': 0,
      '@typescript-eslint/prefer-namespace-keyword': 0,
      '@typescript-eslint/no-empty-function': 0,
      '@typescript-eslint/no-unused-vars': 0,
      '@typescript-eslint/no-explicit-any': 0,
      'block-spacing': ['error', 'always'],
      'keyword-spacing': ['error', { before: true, after: true }],
      'indent': ['error', 2, { SwitchCase: 1 }],
      'linebreak-style': ['error', 'unix'],
      'quotes': ['error', 'single'],
      'semi': ['error', 'never'],
      'comma-dangle': ['error', 'always-multiline'],
      'no-console': 1,
      'object-curly-spacing': ['error', 'always'],
      'space-in-parens': ['error', 'never'],
      'array-bracket-spacing': ['error', 'never'],
      'no-trailing-spaces': 'error',
      'no-multi-spaces': 'error',
      'no-lonely-if': 'error',
      'key-spacing': 'error',
    },
  },
]
