/**
 * Auto-generated app metadata
 * This file is generated at build time to provide app metadata without developer intervention
 */

// This file is automatically generated by the build process
// It extracts metadata from app.json, app.config.js, or package.json

export interface AppMetadata {
  name?: string;
  version?: string;
  bundleId?: string;
  buildNumber?: string;
  displayName?: string;
}

// Auto-detected values from project configuration files
export const APP_METADATA: AppMetadata = {
  name: '@multiplayer-app/session-recorder-react-native',
  version: '0.0.1',
  bundleId: undefined,
  buildNumber: undefined,
  displayName: undefined,
};

/**
 * Get auto-detected app metadata
 */
export function getAutoDetectedAppMetadata(): AppMetadata {
  return { ...APP_METADATA };
}
